---
# Minimal bastion host configuration - SSH jump server only

- name: Update system packages
  dnf:
    name: "*"
    state: latest
    update_cache: true
  become: true

# SSH Security Hardening - MINIMAL and SAFE settings only
- name: Configure SSH security settings
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: true
  become: true
  loop:
    - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin no' }
    - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^#?PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
    - { regexp: '^#?PermitEmptyPasswords', line: 'PermitEmptyPasswords no' }
    - { regexp: '^#?X11Forwarding', line: 'X11Forwarding no' }
    - { regexp: '^#?ClientAliveInterval', line: 'ClientAliveInterval 300' }
    - { regexp: '^#?ClientAliveCountMax', line: 'ClientAliveCountMax 2' }
    - { regexp: '^#?AllowAgentForwarding', line: 'AllowAgentForwarding yes' }
  notify: restart sshd

- name: Set SSH banner
  copy:
    content: |
      ================================================================================
                              BASTION HOST - AUTHORIZED ACCESS ONLY
      ================================================================================

      This system is for authorized users only. All activities are monitored
      and logged. Unauthorized access is strictly prohibited.

      Bastion Host - {{ inventory_hostname }}
      SSH Jump Server Only - No additional tools
      Managed by Ansible
      ================================================================================
    dest: /etc/ssh/ssh_banner
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Configure SSH banner
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Banner'
    line: 'Banner /etc/ssh/ssh_banner'
    state: present
  become: true
  notify: restart sshd

- name: Ensure SSH service is enabled and started
  systemd:
    name: sshd
    state: started
    enabled: true
  become: true

- name: Create completion log
  file:
    path: /var/log/bastion-setup.log
    state: touch
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Log bastion setup completion
  lineinfile:
    path: /var/log/bastion-setup.log
    line: "Minimal bastion host setup completed by Ansible at {{ ansible_date_time.iso8601 }}"
    create: true
  become: true

- name: Display bastion configuration summary
  debug:
    msg:
      - "==============================================="
      - "         MINIMAL BASTION HOST READY"
      - "==============================================="
      - "Host: {{ inventory_hostname }}"
      - "Public IP: {{ ansible_default_ipv4.address }}"
      - "SSH Access: ssh -i ~/.ssh/clo_ec2_001 ec2-user@{{ ansible_default_ipv4.address }}"
      - ""
      - "SSH security configured"
      - "Root login disabled"
      - "Password auth disabled"
      - "Only key-based auth"
      - ""
      - "Purpose: SSH jump server ONLY"
      - "From here, SSH to Docker Swarm nodes"
      - "==============================================="