---
# tasks file for bastion host configuration

- name: Update all packages with dnf
  dnf:
    name: "*"
    state: latest
  become: true

- name: Install essential troubleshooting tools
  dnf:
    name:
      - htop
      - tree
      - wget
      - curl
      - telnet
      - nc
      - nmap-ncat
      - git
      - vim
      - tmux
    state: present
  become: true

- name: Install Docker for troubleshooting
  dnf:
    name: docker
    state: present
  become: true

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes
  become: true

- name: Create log file for bastion setup completion
  file:
    path: /var/log/bastion-setup.log
    state: touch
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Log bastion setup completion
  lineinfile:
    path: /var/log/bastion-setup.log
    line: "Bastion host setup completed by Ansible at {{ ansible_date_time.iso8601 }}"
    create: yes
  become: true

- name: Display bastion host information
  debug:
    msg:
      - "Bastion host configured successfully!"
      - "Public IP: {{ ansible_default_ipv4.address }}"
      - "Hostname: {{ ansible_hostname }}"
      - "Available tools: htop, tree, wget, curl, telnet, nc, nmap, git, vim, tmux, docker"