---
all:
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ~/.ssh/clo_ec2_001
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

bastion_hosts:
  hosts:
    bastion-01:
      ansible_host: BASTION_IP_PLACEHOLDER

docker_swarm:
  children:
    swarm_managers:
      hosts:
        # Manager nodes will be added here dynamically

    swarm_workers:
      hosts:
        # Worker nodes will be added here dynamically