---
# Docker configuration
docker_packages:
  - docker
  - docker-compose

docker_service_state: started
docker_service_enabled: true

# Docker Swarm configuration
swarm_network_interface: eth0
swarm_advertise_addr: "{{ ansible_default_ipv4.address }}"

# Firewall ports for Docker Swarm
swarm_ports:
  - 2377/tcp  # Cluster management
  - 7946/tcp  # Node communication
  - 7946/udp  # Node communication
  - 4789/udp  # Overlay network traffic

# System configuration
timezone: Europe/Stockholm