---
# Docker configuration
docker_packages:
  - docker
  - docker-compose

docker_service_state: started
docker_service_enabled: true

# Docker Swarm configuration
swarm_network_interface: eth0
swarm_advertise_addr: "{{ ansible_default_ipv4.address }}"

# Application configuration
app_name: "clo-fresva-app"
app_image: "haffy/clo-fresva-app:latest"
app_replicas: 3
app_port: 80
app_network: "app-network"
app_data_volume: "app-data-volume"
app_service_name: "clo-fresva-app"

# AWS API configuration
api_gateway_url: "{{ api_gateway_url_from_terraform | default('https://your-api-gateway-url.amazonaws.com/prod') }}"

# Watchtower configuration
watchtower_name: "watchtower"
watchtower_interval: 300  # Check every 5 minutes

# Health check configuration
health_endpoint: "/api/health"
health_retries: 12
health_delay: 10

# Firewall ports for Docker Swarm
swarm_ports:
  - 2377/tcp  # Cluster management
  - 7946/tcp  # Node communication
  - 7946/udp  # Node communication
  - 4789/udp  # Overlay network traffic

# System configuration
timezone: Europe/Stockholm