---
- name: restart docker
  systemd:
    name: docker
    state: restarted
  become: true

- name: reload systemd
  systemd:
    daemon_reload: true
  become: true

- name: restart sshd
  systemd:
    name: sshd
    state: restarted
  become: true