---
- name: Configure Bastion Host
  hosts: bastion_hosts
  become: true
  gather_facts: yes

  tasks:
    - name: Include bastion role
      include_role:
        name: bastion

    - name: Display bastion configuration summary
      debug:
        msg:
          - "==============================================="
          - "       BASTION HOST CONFIGURED"
          - "==============================================="
          - "Host: {{ inventory_hostname }}"
          - "Public IP: {{ ansible_default_ipv4.address }}"
          - "Private IP: {{ ansible_default_ipv4.address }}"
          - "SSH Access: ssh -i ~/.ssh/clo_ec2_001 ec2-user@{{ ansible_default_ipv4.address }}"
          - ""
          - "Available debugging tools:"
          - "  - Docker (for container troubleshooting)"
          - "  - Network tools: curl, wget, nc, telnet, nmap"
          - "  - System tools: htop, tree, vim, tmux"
          - "  - Version control: git"
          - ""
          - "From this bastion host, you can SSH to:"
          - "  - Docker Swarm manager nodes"
          - "  - Docker Swarm worker nodes"
          - "==============================================="