---
- name: Configure Bastion Host
  hosts: bastion_hosts
  become: true
  gather_facts: true

  tasks:
    - name: Include bastion role
      include_role:
        name: bastion

    - name: Display bastion configuration summary
      debug:
        msg:
          - "==============================================="
          - "       MINIMAL BASTION HOST CONFIGURED"
          - "==============================================="
          - "Host: {{ inventory_hostname }}"
          - "Public IP: {{ ansible_default_ipv4.address }}"
          - "SSH Access: ssh -i ~/.ssh/clo_ec2_001 ec2-user@{{ ansible_default_ipv4.address }}"
          - ""
          - "Configuration:"
          - "  - SSH Agent Forwarding: Enabled"
          - "  - Security hardening: Applied"
          - "  - Purpose: SSH jump server ONLY"
          - ""
          - "From this bastion host, you can SSH to:"
          - "  - Docker Swarm manager nodes"
          - "  - Docker Swarm worker nodes"
          - "==============================================="