---
- name: Setup Docker and Docker Swarm
  hosts: docker_swarm
  gather_facts: true

  roles:
    - docker
    - docker_swarm

- name: Setup Docker Swarm Resources
  hosts: swarm_managers[0]
  gather_facts: false

  tasks:
    - name: Create app network
      command: >
        docker network create
        --driver overlay
        --attachable
        {{ app_network }}
      register: network_result
      failed_when:
        - network_result.rc != 0
        - '"already exists" not in network_result.stderr'

    - name: Create shared data volume for database synchronization
      command: >
        docker volume create
        --driver local
        {{ app_data_volume }}
      register: volume_result
      failed_when:
        - volume_result.rc != 0
        - '"already exists" not in volume_result.stderr'

- name: Initialize Docker Swarm
  hosts: swarm_managers
  gather_facts: true
  serial: 1

  roles:
    - docker_swarm

- name: Join workers to Docker Swarm
  hosts: swarm_workers
  gather_facts: true

  roles:
    - docker_swarm

- name: Display Swarm Status
  hosts: swarm_managers[0]
  gather_facts: false

  tasks:
    - name: Get swarm nodes
      command: docker node ls
      register: swarm_nodes
      changed_when: false

    - name: Display swarm nodes
      debug:
        msg: "{{ swarm_nodes.stdout_lines }}"

- name: Deploy Watchtower and Application Services
  hosts: swarm_managers[0]
  gather_facts: false

  tasks:
    - name: Deploy or update Watchtower service
      shell: |
        if docker service ls --filter name={{ watchtower_name }} --format "{{ '{{' }}.Name{{ '}}' }}" | grep -q "{{ watchtower_name }}"; then
          echo "Updating existing Watchtower service..."
          docker service update \
            --env-add WATCHTOWER_POLL_INTERVAL={{ watchtower_interval }} \
            --env-add WATCHTOWER_CLEANUP=true \
            --env-add WATCHTOWER_INCLUDE_RESTARTING=true \
            --env-add WATCHTOWER_ROLLING_RESTART=true \
            --env-add WATCHTOWER_LABEL_ENABLE=true \
            --env-add WATCHTOWER_DEBUG=true \
            --env-add WATCHTOWER_LOG_LEVEL=debug \
            --env-add WATCHTOWER_TIMEOUT=60s \
            --env-add WATCHTOWER_WARN_ON_HEAD_FAILURE=never \
            --env-add WATCHTOWER_NO_RESTART=false \
            --env-add WATCHTOWER_REVIVE_STOPPED=false \
            --env-add WATCHTOWER_IGNORE_IMAGE_ID=true \
            --env-add WATCHTOWER_IGNORE_IMAGE_SHA=true \
            {{ watchtower_name }}
        else
          echo "Creating new Watchtower service..."
          docker service create \
            --name {{ watchtower_name }} \
            --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
            --constraint 'node.role==manager' \
            --env WATCHTOWER_POLL_INTERVAL={{ watchtower_interval }} \
            --env WATCHTOWER_CLEANUP=true \
            --env WATCHTOWER_INCLUDE_RESTARTING=true \
            --env WATCHTOWER_ROLLING_RESTART=true \
            --env WATCHTOWER_LABEL_ENABLE=true \
            --env WATCHTOWER_DEBUG=true \
            --env WATCHTOWER_LOG_LEVEL=debug \
            --env WATCHTOWER_TIMEOUT=60s \
            --env WATCHTOWER_WARN_ON_HEAD_FAILURE=never \
            --env WATCHTOWER_NO_RESTART=false \
            --env WATCHTOWER_REVIVE_STOPPED=false \
            --env WATCHTOWER_IGNORE_IMAGE_ID=true \
            --env WATCHTOWER_IGNORE_IMAGE_SHA=true \
            --label com.centurylinklabs.watchtower.enable=false \
            --restart-condition on-failure \
            --restart-max-attempts 3 \
            containrrr/watchtower:latest
        fi
      register: watchtower_result
      failed_when: false

    - name: Deploy or update application service
      shell: |
        if docker service ls --filter name={{ app_name }} --format "{{ '{{' }}.Name{{ '}}' }}" | grep -q "{{ app_name }}"; then
          echo "Updating existing application service..."
          docker service update \
            --image {{ app_image }} \
            --env-add NODE_ENV=production \
            --env-add LOAD_BALANCED=true \
            --env-add SERVICE_NAME={{ app_service_name }} \
            --env-add CONTAINER_NAME="{{ '{{' }}.Service.Name{{ '}}' }}.{{ '{{' }}.Task.Slot{{ '}}' }}.{{ '{{' }}.Task.ID{{ '}}' }}" \
            --env-add CONTAINER_ID="{{ '{{' }}.Task.ID{{ '}}' }}" \
            --env-add NODE_NAME="{{ '{{' }}.Node.Hostname{{ '}}' }}" \
            --env-add NODE_ID="{{ '{{' }}.Node.ID{{ '}}' }}" \
            --env-add TASK_SLOT="{{ '{{' }}.Task.Slot{{ '}}' }}" \
            --env-add API_GATEWAY_URL={{ api_gateway_url }} \
            --label-add com.centurylinklabs.watchtower.enable=true \
            --label-add com.centurylinklabs.watchtower.monitor-only=false \
            --dns-add 8.8.8.8 \
            --dns-add 1.1.1.1 \
            --update-parallelism 1 \
            --update-delay 30s \
            --update-monitor 10s \
            --update-failure-action rollback \
            --update-max-failure-ratio 0.3 \
            --rollback-parallelism 1 \
            --rollback-delay 10s \
            --rollback-monitor 5s \
            {{ app_name }}
        else
          echo "Creating new application service..."
          docker service create \
            --name {{ app_name }} \
            --replicas {{ app_replicas }} \
            --network {{ app_network }} \
            --publish {{ app_port }}:80 \
            --mount type=volume,source={{ app_data_volume }},target=/app/data \
            --env NODE_ENV=production \
            --env LOAD_BALANCED=true \
            --env SERVICE_NAME={{ app_service_name }} \
            --env CONTAINER_NAME="{{ '{{' }}.Service.Name{{ '}}' }}.{{ '{{' }}.Task.Slot{{ '}}' }}.{{ '{{' }}.Task.ID{{ '}}' }}" \
            --env CONTAINER_ID="{{ '{{' }}.Task.ID{{ '}}' }}" \
            --env NODE_NAME="{{ '{{' }}.Node.Hostname{{ '}}' }}" \
            --env NODE_ID="{{ '{{' }}.Node.ID{{ '}}' }}" \
            --env TASK_SLOT="{{ '{{' }}.Task.Slot{{ '}}' }}" \
            --env API_GATEWAY_URL={{ api_gateway_url }} \
            --hostname="{{ '{{' }}.Service.Name{{ '}}' }}.{{ '{{' }}.Task.Slot{{ '}}' }}.{{ '{{' }}.Task.ID{{ '}}' }}" \
            --label com.centurylinklabs.watchtower.enable=true \
            --label com.centurylinklabs.watchtower.monitor-only=false \
            --dns 8.8.8.8 \
            --dns 1.1.1.1 \
            --restart-condition on-failure \
            --restart-max-attempts 3 \
            --update-parallelism 1 \
            --update-delay 30s \
            --update-failure-action rollback \
            --update-max-failure-ratio 0.3 \
            --rollback-parallelism 1 \
            --rollback-delay 10s \
            {{ app_image }}
        fi
      register: app_result
      failed_when: false

    - name: Debug deployment results
      debug:
        msg: |
          Watchtower deployment result: {{ watchtower_result.rc | default('N/A') }}
          Watchtower output: {{ watchtower_result.stdout | default('No output') }}
          App deployment result: {{ app_result.rc | default('N/A') }}
          App output: {{ app_result.stdout | default('No output') }}

    - name: Display deployment summary
      debug:
        msg: |
          Deployment completed successfully!
          - Watchtower service: {{ watchtower_name }}
          - Application service: {{ app_name }}
          - Watchtower will check for updates every {{ watchtower_interval }}s

    - name: Show all services
      command: docker service ls
      register: services
      changed_when: false

    - name: Display services
      debug:
        msg: "{{ services.stdout_lines }}"