---
- name: Setup Docker and Docker Swarm
  hosts: docker_swarm
  gather_facts: true

  roles:
    - docker
    - docker_swarm

- name: Setup Docker Swarm Resources
  hosts: swarm_managers[0]
  gather_facts: false

  tasks:
    - name: Create app network
      command: >
        docker network create
        --driver overlay
        --attachable
        {{ app_network }}
      register: network_result
      failed_when:
        - network_result.rc != 0
        - '"already exists" not in network_result.stderr'

    - name: Create shared data volume for database synchronization
      command: >
        docker volume create
        --driver local
        {{ app_data_volume }}
      register: volume_result
      failed_when:
        - volume_result.rc != 0
        - '"already exists" not in volume_result.stderr'

- name: Initialize Docker Swarm
  hosts: swarm_managers
  gather_facts: true
  serial: 1

  roles:
    - docker_swarm

- name: Join workers to Docker Swarm
  hosts: swarm_workers
  gather_facts: true

  roles:
    - docker_swarm

- name: Display Swarm Status
  hosts: swarm_managers[0]
  gather_facts: false

  tasks:
    - name: Get swarm nodes
      command: docker node ls
      register: swarm_nodes
      changed_when: false

    - name: Display swarm nodes
      debug:
        msg: "{{ swarm_nodes.stdout_lines }}"

- name: Deploy Watchtower and Application Services
  hosts: swarm_managers[0]
  gather_facts: false

  tasks:
    - name: Check if Watchtower service already exists
      command: docker service ls --filter name={{ watchtower_name }} --format "{{ '{{' }}.Name{{ '}}' }}"
      register: watchtower_exists
      failed_when: false
      changed_when: false

    - name: Deploy Watchtower service
      command: >
        docker service create
        --name {{ watchtower_name }}
        --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock
        --constraint 'node.role==manager'
        --env WATCHTOWER_POLL_INTERVAL={{ watchtower_interval }}
        --env WATCHTOWER_CLEANUP=true
        --env WATCHTOWER_INCLUDE_RESTARTING=true
        --env WATCHTOWER_ROLLING_RESTART=true
        --env WATCHTOWER_LABEL_ENABLE=true
        --env WATCHTOWER_DEBUG=true
        --env WATCHTOWER_LOG_LEVEL=debug
        --env WATCHTOWER_TIMEOUT=60s
        --label com.centurylinklabs.watchtower.enable=false
        --restart-condition on-failure
        --restart-max-attempts 3
        containrrr/watchtower:latest
      register: watchtower_result
      when: watchtower_name not in watchtower_exists.stdout
      failed_when: false

    - name: Debug Watchtower deployment
      debug:
        msg: |
          Watchtower exists check: {{ watchtower_exists.stdout }}
          Watchtower deployment needed: {{ watchtower_name not in watchtower_exists.stdout }}
          Watchtower deployment result: {{ watchtower_result.rc | default('N/A - service already existed') }}

    - name: Check if app image exists
      command: docker manifest inspect {{ app_image }}
      register: image_check
      failed_when: false
      changed_when: false

    - name: Check if app service already exists
      command: docker service ls --filter name={{ app_name }} --format "{{ '{{' }}.Name{{ '}}' }}"
      register: existing_service
      failed_when: false
      changed_when: false

    - name: Display deployment context
      debug:
        msg: |
          Deploying with image: {{ app_image }}
          Service exists: {{ existing_service.stdout | length > 0 }}
          Strategy: Watchtower handles automatic updates of latest images

    - name: Update service only for initial deployment or manual changes (not image updates)
      command: >
        docker service update
        --image {{ app_image }}
        --env-add NODE_ENV=production
        --env-add LOAD_BALANCED=true
        --env-add SERVICE_NAME={{ app_service_name }}
        --env-add CONTAINER_NAME="{{ '{{' }}.Service.Name{{ '}}' }}.{{ '{{' }}.Task.Slot{{ '}}' }}.{{ '{{' }}.Task.ID{{ '}}' }}"
        --env-add CONTAINER_ID="{{ '{{' }}.Task.ID{{ '}}' }}"
        --env-add NODE_NAME="{{ '{{' }}.Node.Hostname{{ '}}' }}"
        --env-add NODE_ID="{{ '{{' }}.Node.ID{{ '}}' }}"
        --env-add TASK_SLOT="{{ '{{' }}.Task.Slot{{ '}}' }}"
        --env-add API_GATEWAY_URL={{ api_gateway_url }}
        --update-parallelism 1
        --update-delay 30s
        --update-monitor 10s
        --update-failure-action rollback
        --update-max-failure-ratio 0.3
        --rollback-parallelism 1
        --rollback-delay 10s
        --rollback-monitor 5s
        {{ app_name }}
      register: app_update_result
      when: existing_service.stdout | length > 0  # Update existing service with new config
      failed_when: false

    - name: Docker Swarm Service Setup (first deployment)
      command: >
        docker service create
        --name {{ app_name }}
        --replicas {{ app_replicas }}
        --network {{ app_network }}
        --publish {{ app_port }}:80
        --mount type=volume,source={{ app_data_volume }},target=/app/data
        --env NODE_ENV=production
        --env LOAD_BALANCED=true
        --env SERVICE_NAME={{ app_service_name }}
        --env CONTAINER_NAME="{{ '{{' }}.Service.Name{{ '}}' }}.{{ '{{' }}.Task.Slot{{ '}}' }}.{{ '{{' }}.Task.ID{{ '}}' }}"
        --env CONTAINER_ID="{{ '{{' }}.Task.ID{{ '}}' }}"
        --env NODE_NAME="{{ '{{' }}.Node.Hostname{{ '}}' }}"
        --env NODE_ID="{{ '{{' }}.Node.ID{{ '}}' }}"
        --env TASK_SLOT="{{ '{{' }}.Task.Slot{{ '}}' }}"
        --env API_GATEWAY_URL={{ api_gateway_url }}
        --hostname="{{ '{{' }}.Service.Name{{ '}}' }}.{{ '{{' }}.Task.Slot{{ '}}' }}.{{ '{{' }}.Task.ID{{ '}}' }}"
        --label com.centurylinklabs.watchtower.enable=true
        --restart-condition on-failure
        --restart-max-attempts 3
        --update-parallelism 1
        --update-delay 30s
        --update-failure-action rollback
        --update-max-failure-ratio 0.3
        --rollback-parallelism 1
        --rollback-delay 10s
        {{ app_image }}
      register: app_create_result
      when: existing_service.stdout | length == 0
      failed_when: false

    - name: Set deployment result
      set_fact:
        app_result: "{{ app_update_result if (existing_service.stdout | length > 0) else app_create_result if (existing_service.stdout | length == 0) else {'rc': 0, 'stdout': 'No update needed', 'stderr': '', 'changed': false} }}"

    - name: Wait for rolling update to complete
      command: docker service ps {{ app_name }} --filter "desired-state=running" --format "{{ '{{' }}.CurrentState{{ '}}' }}"
      register: update_status
      until: update_status.stdout_lines | select('match', '^Running.*') | list | length >= (app_replicas | int)
      retries: 20
      delay: 10
      when: app_result.rc is defined and app_result.rc == 0

    - name: Clean up old/unused images on all nodes
      command: docker image prune -f
      when: app_result.rc is defined and app_result.rc == 0
      failed_when: false
      changed_when: false

    - name: Verify service health after update
      command: docker service ps {{ app_name }} --format "{{ '{{' }}.Name{{ '}}' }}\t{{ '{{' }}.CurrentState{{ '}}' }}\t{{ '{{' }}.Error{{ '}}' }}"
      register: service_status
      failed_when: false
      changed_when: false

    - name: Debug app deployment result
      debug:
        msg: |
          App deployment result:
          - Return code: {{ app_result.rc }}
          - Stdout: {{ app_result.stdout }}
          - Stderr: {{ app_result.stderr }}

    - name: Show all services after deployment
      command: docker service ls
      register: services_debug
      changed_when: false

    - name: Display all services
      debug:
        msg: "{{ services_debug.stdout_lines }}"

    - name: Check app service status
      command: docker service ps {{ app_name }} --no-trunc
      register: app_service_status
      failed_when: false
      changed_when: false

    - name: Display app service status
      debug:
        msg: "{{ app_service_status.stdout_lines }}"
      when: app_service_status.rc == 0

    - name: Display image not found message
      debug:
        msg: |
          Image {{ app_image }} not found
          Deploy your frontend app first to make this image available
          Expected behavior: ALB will show 502 until frontend is deployed
      when: image_check.rc != 0

    - name: Display successful deployment message
      debug:
        msg: |
          Application service deployed successfully
          App running on port 80 (Nginx serving React app)
          Health check: curl http://localhost:3000/api/health
      when: image_check.rc == 0 and app_result.rc == 0

    - name: Display deployment failure message
      debug:
        msg: "Service deployment failed: {{ app_result.stderr | default('Unknown error') }}"
      when: image_check.rc == 0 and app_result.rc != 0

    - name: Show service status
      command: docker service ls
      register: service_list
      changed_when: false

    - name: Display services
      debug:
        msg: "{{ service_list.stdout_lines }}"

    - name: Wait for application to be healthy
      uri:
        url: "http://{{ ansible_default_ipv4.address }}{{ health_endpoint | default('/api/health') }}"
        method: GET
        status_code: 200
      register: health_check
      until: health_check.status == 200
      retries: "{{ health_retries | default(12) }}"
      delay: "{{ health_delay | default(10) }}"
      ignore_errors: true

    - name: Set watchtower status
      set_fact:
        watchtower_status: "{{ 'Created' if (watchtower_result is defined and watchtower_result.changed) else 'Already exists' }}"

    - name: Set app service status
      set_fact:
        app_service_status: "{{ 'Created' if (app_result is defined and app_result.changed) else 'Already exists' }}"

    - name: Set health check status
      set_fact:
        health_status: "{{ 'Healthy' if health_check.status == 200 else 'Failed' }}"

    - name: Display deployment summary
      debug:
        msg: |
          Deployment completed!
          - Watchtower: {{ watchtower_status }}
          - App Service: {{ app_service_status }}
          - Health Check: {{ health_status }}
          - Application URL: http://{{ ansible_default_ipv4.address }}
          - Watchtower will check for updates every {{ watchtower_interval }}s

    - name: Show service status
      command: docker service ls
      register: services
      changed_when: false

    - name: Display services
      debug:
        msg: "{{ services.stdout_lines }}"

    - name: Check Watchtower logs for debugging
      command: docker service logs {{ watchtower_name }} --tail 20
      register: watchtower_logs
      failed_when: false
      changed_when: false

    - name: Display Watchtower logs
      debug:
        msg: |
          Recent Watchtower logs:
          {{ watchtower_logs.stdout_lines | join('\n') }}
      when: watchtower_logs.rc == 0

    - name: Force Watchtower to check now (manual trigger)
      command: docker service update --force {{ watchtower_name }}
      register: watchtower_trigger
      failed_when: false
      changed_when: false

    - name: Display Watchtower trigger result
      debug:
        msg: |
          Watchtower manual check triggered
          Result: {{ watchtower_trigger.rc }}
          This forces Watchtower to check for new images immediately