---
- name: Update system packages
  dnf:
    name: "*"
    state: latest
    update_cache: true
  become: true

- name: Install required packages
  dnf:
    name:
      - docker
      - python3-pip
    state: present
  become: true

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present
  become: true

- name: Start and enable Docker service
  systemd:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
  become: true
  notify: restart docker

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: true
  become: true
  notify: restart docker

- name: Configure Docker daemon
  copy:
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        },
        "storage-driver": "overlay2"
      }
    dest: /etc/docker/daemon.json
    mode: '0644'
  become: true
  notify: restart docker

- name: Ensure Docker is running
  systemd:
    name: docker
    state: started
  become: true