# AWS EC2 dynamic inventory configuration
# URL: https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html
# Info: Is used for dynamic inventory of EC2 instances in Ansible

plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1

# Filter instances by specific tags or states
filters:
  instance-state-name: running

# Define group names based on tags
keyed_groups:
  # Create groups based on Role tag: tag_Role_swarm_manager, tag_Role_swarm_worker, tag_Role_bastion
  - key: tags.Role
    prefix: tag_Role
    separator: "_"

  # Create groups based on instance type
  - key: instance_type
    prefix: type

  # Create groups based on availability zone
  - key: placement.availability_zone
    prefix: az

# Create standard group names expected by playbooks
groups:
  # Docker Swarm groups - hosts matching Role tags
  docker_swarm: tags.Role in ['swarm-manager', 'swarm-worker']
  swarm_managers: tags.Role == 'swarm-manager'
  swarm_workers: tags.Role == 'swarm-worker'
  # Bastion group (separate, not in docker_swarm)
  bastion_hosts: tags.Role == 'bastion'

# Compose variables from instance metadata
compose:
  # Bastion uses public IP, swarm nodes use private IP.
  # Checks if public_ip_address exists, otherwise falls back to private_ip_address.
  # So it's important that bastion has a public IP, and swarm nodes do not.
  ansible_host: public_ip_address | default(private_ip_address)
  ansible_user: ec2-user
  # SSH settings will be configured via environment variables
  ec2_state: state.name
  ec2_instance_type: instance_type
  ec2_placement_az: placement.availability_zone
  ec2_vpc_id: vpc_id
  ec2_subnet_id: subnet_id

# Use private IP for instances without public IP (swarm nodes).
hostnames:
  - private-ip-address
  - dns-name
  - name

# Cache settings for better performance
cache: true
cache_plugin: jsonfile
cache_timeout: 300
cache_connection: ~/.ansible/tmp/aws_inventory_cache